// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Models;

#nullable disable

namespace NationalParks.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20230827204912_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkCity")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkState")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkCity = "Grand Canyon Village",
                            ParkName = "Grand Canyon",
                            ParkState = "Arizona",
                            Rating = 9
                        },
                        new
                        {
                            ParkId = 2,
                            ParkCity = "Yosemite National Park",
                            ParkName = "Yosemite",
                            ParkState = "California",
                            Rating = 9
                        },
                        new
                        {
                            ParkId = 3,
                            ParkCity = "Furnace Creek",
                            ParkName = "Death Valley",
                            ParkState = "California",
                            Rating = 8
                        },
                        new
                        {
                            ParkId = 4,
                            ParkCity = "Hawaii National Park",
                            ParkName = "Hawaii Volcanoes",
                            ParkState = "Hawaii",
                            Rating = 10
                        },
                        new
                        {
                            ParkId = 5,
                            ParkCity = "Crescent City",
                            ParkName = "RedWood",
                            ParkState = "California",
                            Rating = 7
                        },
                        new
                        {
                            ParkId = 6,
                            ParkCity = "New City",
                            ParkName = "New",
                            ParkState = "New York",
                            Rating = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
